### ISSUE TITLE
Directory is Empty

### ISSUE THREAD

**Issue by nomadicjosh** [atlet/PHPBackupScript#1]
I've been testing this out but when you untar the directory backup, it is always empty.

**Comment by nomadicjosh** [comment]
MySQL table backups are empty as well.

**Comment by atlet** [comment]
Put error_reporting(-1); in config.php after <?php and run from cli (php backup-s3.php), to see if you receive any errors.

**Comment by nomadicjosh** [comment]
It worked on a live server. However, this may only be my use case, but I had to change:

```
$commandSQL = "mysqldump --add-drop-table --routines -u {$mySqlUsername} -p{$mySqlPassword} {$value} | gzip > " . $backupSqlFile;
```

to this:

```
$commandSQL = "mysqldump --add-drop-table --routines -u {$mySqlUsername} -p{$mySqlPassword} {$mySqlDbName} {$value} | gzip > " . $backupSqlFile;
```

I added the $mySqlDbName variable under MySQL credentials because {$value} was being seen as the database name and therefore my dump files were empty.

**Comment by atlet** [comment]
Where do you define $mySqlDbName?

**Comment by nomadicjosh** [comment]
I defined it in config.php with the rest of the mysql variables:

```
// MySQL credentials
$mySqlUsername = "username";
$mySqlPassword = "password";
$mySqlDbName = "dbname";
```

**Comment by atlet** [comment]
Ok, did you rename config.php.example to config.php and added db names to $sqlTables variable?

**Comment by nomadicjosh** [comment]
Yes and yes. Everything works for me now on a live server with the added $dbname variable.
